import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


import ClientOnly from "../components/ClientOnly";
import Products from "../components/Products";
import Navbar from "../components/Navbar";
import Cart from "../components/Cart";

const Home: NextPage = () => {
  return (
    <div className="bg-gray-200">
      <Head>
        <title>LUMINSKIN - Pangaea Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className="">
        <Navbar />

        <ClientOnly>
          <Products />
          <Cart />
        </ClientOnly>


      </main>

    </div>
  );
}

export default Home